# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Quality

on:
  push:
    branches: [ "2.x", "issue_17_failed_message_never_retried" ]
  pull_request:
    branches: [ "2.x" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    strategy:
      matrix:
        php: ['8.0', '8.1', '8.2', '8.3']
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.11
        ports:
          - 3306:3306
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: nopassword
          MYSQL_DATABASE: app
          MYSQL_ROOT_PASSWORD: nopassword
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3


    env:
      DATABASE_URL: mysql://root:nopassword@127.0.0.1:3306/app?serverVersion=mariadb-10.11.2&charset=utf8mb4

    steps:
      #  To automatically get bug fixes and new Php versions for shivammathur/setup-php,
      # change this to (see https://github.com/shivammathur/setup-php#bookmark-versioning):
      # uses: shivammathur/setup-php@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - uses: actions/checkout@v4
#      - name: Copy .env.test.local
#        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Create Database
        run: |
          cd tests/Application
          bin/console doctrine:migration:migrate -n
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit
